PREFIX = '[MIDIPACKS]'

logger =
  info: (args...) -> console.info PREFIX, args...
  error: (args...) -> console.error PREFIX, args...
  warn: (args...) -> console.warn PREFIX, args...

module.exports = { logger }
